CheckNip/Models/Person.cs
using Newtonsoft.Json;

namespace CheckNip.Models
{
    public class Person
    {
        [JsonProperty("firstName")]
        public string? FirstName { get; set; }

        [JsonProperty("lastName")]
        public string? LastName { get; set; }

        [JsonProperty("PESEL")]
        public string? pesel { get; set; }

        [JsonProperty("nip")]      
        public string? Nip { get; set; }

        [JsonProperty("companyName")]
        public string? CompanyName { get; set; }
    }
}

CheckNip/Models/Result.cs
using Newtonsoft.Json;

namespace CheckNip.Models
{
    public class Result
    {
        [JsonProperty("subject")]
        public Subject Subject { get; set; }

        [JsonProperty("requestDateTime")]
        public string RequestDateTime { get; set; }

        [JsonProperty("requestId")]
        public string RequestId { get; set; }
    }

    public class ResultRoot
    {
        [JsonProperty("result")]
        public Result Result { get; set; }
    }
}

CheckNip/Models/Subject.cs
using Newtonsoft.Json;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CheckNip.Models
{
    public class Subject
    {
        public int Id { get; set; }

        [JsonProperty("regon")]
        [DisplayName("REGON")]
        public string? Regon { get; set; }

        [JsonProperty("restorationDate")]
        [DisplayName("Data przywrócenia jako podatnika VAT")]
        public DateTime? RestorationDate { get; set; }

        [JsonProperty("workingAddress")]
        [DisplayName("Adres rejestracyjny")]
        public string? WorkingAddress { get; set; }

        [JsonProperty("hasVirtualAccounts")]
        [DisplayName("Podmiot posiada maski kont wirtualnych")]
        public bool HasVirtualAccounts { get; set; }

        [JsonProperty("statusVat")]
        [DisplayName("Status podatnika VAT")]
        public string? StatusVat { get; set; }

        [JsonProperty("krs")]
        [DisplayName("numer KRS jeżeli został nadany")]
        public string? Krs { get; set; }

        [JsonProperty("restorationBasis")]
        [DisplayName("Podstawa prawna przywrócenia jako podatnika VAT")]
        public string? RestorationBasis { get; set; }

        [JsonProperty("accountNumbers")]
        [DisplayName("Numery kont bankowych")]
        public List<string>? AccountNumbers { get; set; }

        [JsonProperty("registrationDenialBasis")]
        [DisplayName("Podstawa prawna odmowy rejestracji")]
        public string? RegistrationDenialBasis { get; set; }

        [JsonProperty("nip")]
        [DisplayName("NIP")]
        public string? Nip { get; set; }

        [JsonProperty("removalDate")]
        [DisplayName("Data wykreślenia odmowy rejestracji jako podatnika VAT")]
        public DateTime? RemovalDate { get; set; }

        [JsonProperty("partners")]
        [DisplayName("Imiona i nazwiska lub firmę (nazwa) wspólnika")]
        public List<Person>? Partners { get; set; }

        [JsonProperty("name")]
        [DisplayName("Firma (nazwa) lub imię i nazwisko")]
        public string? Name { get; set; }

        [JsonProperty("registrationLegalDate")]
        [DisplayName("Data rejestracji jako podatnika VAT ")]
        public DateTime? RegistrationLegalDate { get; set; }

        [JsonProperty("removalBasis")]
        [DisplayName("Podstawa prawna wykreślenia odmowy rejestracji jako podatnika VAT")]
        public string? RemovalBasis { get; set; }

        [JsonProperty("pesel")]
        [DisplayName("PESEL")]
        public string? Pesel { get; set; }

        [JsonProperty("representatives")]
        [DisplayName("Imiona i nazwiska osób wchodzących w skład organu uprawnionego do reprezentowania podmiotu")]
        public List<Person>? Representatives { get; set; }

        [JsonProperty("residenceAddress")]
        [DisplayName("Adres siedziby działalności gospodarczej")]
        public string? ResidenceAddress { get; set; }

        [JsonProperty("registrationDenialDate")]
        [DisplayName("Data odmowy rejestracji jako podatnika VAT format")]
        public DateTime? RegistrationDenialDate { get; set; }


    }
}

CheckNip/Controllers/HomeController.cs
using AutoMapper;
using CheckNip.DB;
using CheckNip.DB.Models;
using CheckNip.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;
using System.Diagnostics;
using System.Net;
using CheckNip.MockData;

namespace CheckNip.Controllers
{
    public class HomeController : Controller
    {
        private readonly CheckNipContext _context;
        private readonly IMapper _mapper;
        private static ResultRoot _resultRoot;
        
        public HomeController(CheckNipContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;   
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Search(string nip)
        {
            string date = $"?date={DateTime.Now.ToString("yyyy-MM-dd")}";
            string apiUrl = $"https://wl-api.mf.gov.pl/api/search/nip/{nip + date}";

            using (WebClient client = new WebClient())
            {
                try
                {
                    string json = await client.DownloadStringTaskAsync(apiUrl);
                    //string json = Data.jsonResult;//dla testow

                    _resultRoot = JsonConvert.DeserializeObject<ResultRoot>(json);                  
                }
                catch (WebException ex)
                {
                    ViewBag.ErrorMessage = $"Wystąpił błąd podczas pobierania danych. Sprawdź poprawność numeru NIP.";
                    return View("Index");
                }
                try
                {
                    SubjectDb subjectDb = _mapper.Map<SubjectDb>(_resultRoot.Result.Subject);
                    if (subjectDb != null)
                    {
                        _context.Add(subjectDb);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (Exception)
                {
                    ViewBag.ErrorMessage = "Błąd przy zapisie do bazy danych";                   
                }
               
                return View("Result", _resultRoot);
            }
        }
    }
}

CheckNip/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CheckNip.DB;
using CheckNip.DB.Models;
using CheckNip.Models;

namespace CheckNip.Controllers
{
    public class SubjectController : Controller
    {
        private readonly CheckNipContext _context;

        public SubjectController(CheckNipContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var subjects = _context.Subjects.ToList();
            return View(subjects);
        }

        public async Task<IActionResult> Details(int? id)
        {            
            if (id == null || _context.Subjects == null)
            {
                return NotFound();
            }

            var subjectDb = await _context.Subjects.Include(a => a.AccountNumbers).Include(r => r.Representatives).Include(p=>p.Partners)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subjectDb == null)
            {
                return NotFound();
            }

            return View(subjectDb);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Subjects == null)
            {
                return NotFound();
            }

            var subjectDb = await _context.Subjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subjectDb == null)
            {
                return NotFound();
            }

            return View(subjectDb);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Subjects == null)
            {
                return Problem("Błąd przy usuwaniu danych, nie pobrano danych do usunięcia.");
            }
            var subjectDb = await _context.Subjects.FindAsync(id);
            if (subjectDb != null)
            {
                _context.Subjects.Remove(subjectDb);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubjectDbExists(int id)
        {
          return (_context.Subjects?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CheckNip/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Wyszukiwanie po numerze NIP";
}

<div class="text-center">
    @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
    {
        <div class="alert alert-danger">@ViewBag.ErrorMessage</div>
    }
    <div class="container mt-3">       
        <div class="mt-4 p-5 bg-light text-black rounded">
            <h1>Pobierz dane podmiotu</h1>           
            <p>Aplikacja umożliwia pobranie danych kontrahenta z ogólnej bazy danych na podstawie numeru NIP</p>           
            <form asp-controller="Home" asp-action="Search" method="post">               
                <div class="form-group">
                    <input type="text" onkeypress='validate(event)' id="nip" name="nip" class="form-control center-block" placeholder="Wprowadź nip" required />
                </div>
                <br/>
                <button type="submit" class="btn btn-lg btn-outline-dark">Szukaj</button>
            </form>
        </div>
    </div>

   
</div>

CheckNip/Views/Home/Result.cshtml
@model CheckNip.Models.ResultRoot

@{
    ViewData["Title"] = "Result";
}

<div class="container mt-3">
    <h2>Nazwa firmy: @Model.Result.Subject.Name</h2>
    <br>
    <!-- Nav pills -->
    <ul class="nav bg-light nav-pills greyNav" role="tablist">
        <li class="nav-item">
            <a class="nav-link text-dark active" data-bs-toggle="pill" href="#home">Ogólne</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark " data-bs-toggle="pill" href="#account">Konta bankowe</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" data-bs-toggle="pill" href="#partners">Wspólnicy</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" data-bs-toggle="pill" href="#representative">Reprezentanci</a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div id="home" class="container tab-pane active">
            <div class="card-body">
                <p class="card-text">
                    @if (Model != null)
                    {
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">Nazwa</th>
                                    <th scope="col">Dane podmiotu</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(Model => Model.Result.Subject.Regon)</th>
                                    <td>@Html.DisplayFor(model => Model.Result.Subject.Regon)</td>
                                </tr>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(model => Model.Result.Subject.RestorationDate)</th>
                                    <td>@Html.DisplayFor(model => Model.Result.Subject.RestorationDate)</td>
                                </tr>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(model => Model.Result.Subject.WorkingAddress)</th>
                                    <td colspan="2">@Html.DisplayFor(model => Model.Result.Subject.WorkingAddress)</td>
                                </tr>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(model => Model.Result.Subject.HasVirtualAccounts)</th>
                                    <td colspan="2">@Html.DisplayFor(model => Model.Result.Subject.HasVirtualAccounts)</td>
                                </tr>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(model => Model.Result.Subject.StatusVat)</th>
                                    <td colspan="2">@Html.DisplayFor(model => Model.Result.Subject.StatusVat)</td>
                                </tr>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(model => Model.Result.Subject.Krs)</th>
                                    <td colspan="2">@Html.DisplayFor(model => Model.Result.Subject.Krs)</td>
                                </tr>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(model => Model.Result.Subject.RestorationBasis)</th>
                                    <td colspan="2">@Html.DisplayFor(model => Model.Result.Subject.RestorationBasis)</td>
                                </tr>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(model => Model.Result.Subject.RegistrationDenialBasis)</th>
                                    <td colspan="2">@Html.DisplayFor(model => Model.Result.Subject.RegistrationDenialBasis)</td>
                                </tr>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(model => Model.Result.Subject.Nip)</th>
                                    <td colspan="2">@Html.DisplayFor(model => Model.Result.Subject.Nip)</td>
                                </tr>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(model => Model.Result.Subject.RemovalDate)</th>
                                    <td colspan="2">@Html.DisplayFor(model => Model.Result.Subject.RemovalDate)</td>
                                </tr>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(model => Model.Result.Subject.Name)</th>
                                    <td colspan="2">@Html.DisplayFor(model => Model.Result.Subject.Name)</td>
                                </tr>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(model => Model.Result.Subject.RegistrationLegalDate)</th>
                                    <td colspan="2">@Html.DisplayFor(model => Model.Result.Subject.RegistrationLegalDate)</td>
                                </tr>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(model => Model.Result.Subject.RemovalBasis)</th>
                                    <td colspan="2">@Html.DisplayFor(model => Model.Result.Subject.RemovalBasis)</td>
                                </tr>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(model => Model.Result.Subject.Pesel)</th>
                                    <td colspan="2">@Html.DisplayNameFor(model => Model.Result.Subject.Pesel)</td>
                                </tr>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(model => Model.Result.Subject.ResidenceAddress)</th>
                                    <td colspan="2">@Html.DisplayFor(model => Model.Result.Subject.ResidenceAddress)</td>
                                </tr>
                                <tr>
                                    <th scope="row">@Html.DisplayNameFor(model => Model.Result.Subject.RegistrationDenialDate)</th>
                                    <td colspan="2">@Html.DisplayFor(model => Model.Result.Subject.RegistrationDenialDate)</td>
                                </tr>
                            </tbody>
                        </table>
                    }
                </p>

            </div>
        </div>
        <div id="account" class="container tab-pane fade">
            <br>
            @if (Model != null)
            {
                <dl class="row">
                    <dt class="col-sm-5">
                        @Html.DisplayNameFor(model => Model.Result.Subject.AccountNumbers)
                    </dt>
                    <dd class="col-sm-10">
                        @if (Model.Result.Subject.AccountNumbers != null)
                            @foreach (var account in Model.Result.Subject.AccountNumbers)
                            {
                                @account <br />
                            }
                    </dd>
                </dl>
               
            }
        </div>
        <div id="partners" class="container tab-pane fade">
            <br>  
            @if (Model.Result.Subject.Partners != null)
            {
                @foreach (var partner in Model.Result.Subject.Partners)
                {
                    @partner.FirstName <br />
                    @partner.LastName <br />
                    @partner.Nip <br />
                    @partner.pesel <br />
                    @partner.CompanyName <br />
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Nazwa</th>
                                <th scope="col">Dane wspólnika</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <th scope="row">@Html.DisplayName("Imie")</th>
                                <td>@partner.FirstName</td>
                            </tr>
                            <tr>
                                <th scope="row">@Html.DisplayName("Nazwisko")</th>
                                <td>@partner.LastName</td>
                            </tr>
                            <tr>
                                <th scope="row">@Html.DisplayName("NIP")</th>
                                <td colspan="2"> @partner.Nip</td>
                            </tr>
                            <tr>
                                <th scope="row">@Html.DisplayName("PESEL")</th>
                                <td colspan="2">@partner.pesel</td>
                            </tr>
                            <tr>
                                <th scope="row">@Html.DisplayName("Nazwa firmy")</th>
                                <td colspan="2">@partner.CompanyName</td>
                            </tr>

                        </tbody>
                    </table>
                }
            }
        </div>
        <div id="representative" class="container tab-pane fade">
            <br>
            @if (Model.Result.Subject.Representatives != null)
            {
                @foreach (var partner in Model.Result.Subject.Representatives)
                {
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Nazwa</th>
                                <th scope="col">Dane wspólnika</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <th scope="row">@Html.DisplayName("Imie")</th>
                                <td>@partner.FirstName</td>
                            </tr>
                            <tr>
                                <th scope="row">@Html.DisplayName("Nazwisko")</th>
                                <td>@partner.LastName</td>
                            </tr>
                            <tr>
                                <th scope="row">@Html.DisplayName("NIP")</th>
                                <td colspan="2"> @partner.Nip</td>
                            </tr>
                            <tr>
                                <th scope="row">@Html.DisplayName("PESEL")</th>
                                <td colspan="2">@partner.pesel</td>
                            </tr>
                            <tr>
                                <th scope="row">@Html.DisplayName("Nazwa firmy")</th>
                                <td colspan="2">@partner.CompanyName</td>
                            </tr>

                        </tbody>
                    </table>
                }
            }
        </div>
    </div>
</div>

<div>    
    <a class="btn btn-outline-dark" asp-action="Index">Wstecz</a>
</div>

CheckNip/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CheckNip</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CheckNip.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm bg-light navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand text-black" asp-area="" asp-controller="Home" asp-action="Index">Checknip</a>              
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Start</a>                           
                        </li>
                        <li class="nav-item">                           
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subject" asp-action="Index">Sprawdzone podmioty</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - eNIP - Maciej Łącki-
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        function validate(evt) {
            var theEvent = evt || window.event;

            // Handle paste
            if (theEvent.type === 'paste') {
                key = event.clipboardData.getData('text/plain');
            } else {
                // Handle key press
                var key = theEvent.keyCode || theEvent.which;
                key = String.fromCharCode(key);
            }
            var regex = /[0-9]|\./;
            if (!regex.test(key)) {
                theEvent.returnValue = false;
                if (theEvent.preventDefault) theEvent.preventDefault();
            }
        }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CheckNip/Views/Subject/Delete.cshtml
@model CheckNip.DB.Models.SubjectDb

@{
    ViewData["Title"] = "Usuń";
}

<h1>Usuwanie</h1>

<h3>Czy chcesz usunąć podmiot z bazy?</h3>
<div>
    <h4>@Html.DisplayFor(model => model.Nip)</h4>
    <hr />
    <dl class="row">     
        <dt class="col-sm-2">
            @Html.DisplayName("Status vat")
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatusVat)
        </dd>       
        <dt class = "col-sm-2">
            @Html.DisplayName("Nazwa podmiotu")
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>      
        <dt class = "col-sm-2">
            @Html.DisplayName("Adres")
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ResidenceAddress)
        </dd>      
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Usuń" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-outline-dark">Wstecz</a>
    </form>
</div>

CheckNip/Views/Subject/Index.cshtml
@model IEnumerable<CheckNip.DB.Models.SubjectDb>

@{
    ViewData["Title"] = "Sprawdzone podmioty";
}

<div class="container mt-3">
    <h2>Sprawdzone podmioty</h2>
    <table class="table table-bordered">
        <thead class="bg-light" >
            <tr>
                <th>
                    @Html.DisplayName("Status vat")
                </th>
                <th>
                    @Html.DisplayName("Numer NIP")
                </th>
                <th>
                    @Html.DisplayName("Nazwa podmiotu")
                </th>
                <th>
                    @Html.DisplayName("Data rejestracji")
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.StatusVat)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nip)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RegistrationLegalDate)
                    </td>
                    <td>
                        <a class="btn btn-outline-dark" asp-action="Details" asp-route-id="@item.Id">Szczegóły</a>
                        <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Usuń</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>